name: sirix_client

packages:
  - apps/**
  - packages/**

scripts:
  bootstrap:
    run: melos bootstrap
    description: Bootstrap all Flutter/Dart packages.

  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze for all packages.

  test:
    run: melos exec -- flutter test
    description: Run flutter test for all packages.
